from datetime import datetime
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class AuthContext(BaseModel):
    provider: str = Field(description="email provider auth accesses")
    access_token: str
    refresh_token: str
    scopes: list[str] = Field(description="list of scopes token has access to")
    expires_in: int = Field(description="time to expiry in seconds")
    email: str = Field(description="email of token requester")
    id: UUID = Field(description="unique uuid identifier for the id", default=uuid4())


class EmailContext(BaseModel):
    id: str = Field(description="ID for each email generated by api")
    provider: str = Field(description="email service object was fetched from")
    subject: str
    sender_name: str
    sender_email: str
    recieved_at: datetime = Field(default=datetime.now())
    body_text: str
    receipt_ids: list[str]
    file_destination: str = Field(
        description="local filepath for the documents storage"
    )


class ReceiptContext(BaseModel):
    id: str = Field(description="ID for the attached file generated by the api")
    email_id: str = Field(description="ID for the email this rec belongs to")
    vendor: str = Field(description="Who the transaction was from")
    total_cost: float
    date_of_transaction: datetime = Field(default=datetime.now())
